repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
  - id: check-yaml
  - id: check-merge-conflict
  - id: check-toml
  - id: fix-byte-order-marker
  - id: mixed-line-ending
  - id: requirements-txt-fixer

- repo: https://github.com/igorshubovych/markdownlint-cli
  rev: v0.32.2
  hooks:
  - id: markdownlint-fix

- repo: https://github.com/MarcoGorelli/absolufy-imports
  rev: v0.3.1
  hooks:
    - id: absolufy-imports

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.4.9
  hooks:
    - id: ruff
    - id: ruff-format

- repo: https://github.com/jendrikseipp/vulture
  rev: v2.3
  hooks:
    - id: vulture
