"""Sanity checks on whatever `data/03_primary`/`data/04_aggregated` currently
hold on disk.

Unlike `data/01_raw` (committed to the repo — see `.github/workflows/ci.yml`),
`data/03_primary` and `data/04_aggregated` are gitignored build artifacts
produced locally by `make aggregate` / `cartola aggregate`; nothing here is
ever committed. These tests exist to catch a stale or manually-edited local
artifact (e.g. generated by an older pipeline version, or hand-edited) before
it is consumed by downstream analysis — they skip gracefully when the files
are simply absent (e.g. a fresh checkout that has not run the pipeline yet).
"""

from pathlib import Path

import pandas as pd
import pytest

from cartola.aggregation.catalog import YEAR_REGISTRY
from cartola.aggregation.schema import AggregatedSchema

REPO_ROOT = Path(__file__).resolve().parent.parent.parent
PRIMARY_DIR = REPO_ROOT / "data" / "03_primary"
AGGREGATED_CSV = REPO_ROOT / "data" / "04_aggregated" / "cartola_2014_2026.csv"


def _require(path: Path) -> None:
    if not path.exists():
        pytest.skip(f"{path} not present — run `make aggregate` to generate it first")


def test_generated_aggregated_csv_matches_schema():
    _require(AGGREGATED_CSV)
    df = pd.read_csv(AGGREGATED_CSV, low_memory=False)
    AggregatedSchema.validate(df)


def test_generated_aggregated_csv_is_concat_of_primary_years():
    _require(AGGREGATED_CSV)
    for year in YEAR_REGISTRY:
        _require(PRIMARY_DIR / f"cartola_{year}.csv")

    agg = pd.read_csv(AGGREGATED_CSV, low_memory=False)
    total_primary_rows = sum(
        len(pd.read_csv(PRIMARY_DIR / f"cartola_{y}.csv", low_memory=False)) for y in YEAR_REGISTRY
    )
    assert len(agg) == total_primary_rows, (
        f"Aggregated row count ({len(agg)}) does not match the sum of per-year "
        f"primary CSVs ({total_primary_rows}) — did you forget to re-run "
        "`make aggregate` after editing a year's raw data?"
    )


def test_generated_aggregated_csv_has_no_duplicate_keys():
    _require(AGGREGATED_CSV)
    agg = pd.read_csv(AGGREGATED_CSV, low_memory=False)
    dups = agg.duplicated(subset=["ano", "rodada", "id_atleta"]).sum()
    assert dups == 0, f"{dups} duplicate (ano, rodada, id_atleta) rows in the on-disk aggregated CSV"
