# This is a boilerplate parameters config generated for pipeline 'preprocessing'
# using Kedro 0.18.2.
#
# Documentation for this file format can be found in "Parameters"
# Link: https://kedro.readthedocs.io/en/0.18.2/kedro_project_setup/configuration.html#parameters

2021.preprocessing.scouts:
  # ataque
  G: 8.0    # Gol marcado
  A: 5.0    # Assistência
  FT: 3.0   # Finalização na Trave
  FD: 1.2   # Finalização Defendida
  FF: 0.8   # Finalização para Fora
  FS: 0.5   # Falta Sofrida
  PS: 1.0   # Pênalti Sofrido
  PP: -4.0  # Pênalti Perdido
  I: -0.5   # Impedimento
  PI: -0.1  # Passe Incompleto **
  # defesa
  SG: 5.0   # jogo sem Sofrer Gols (somente defensores)
  CV: -5.0  # Cartão Vermelho
  CA: -2.0  # Cartão Amarelo
  GS: -1.0  # Gol Sofrido
  FC: -0.5  # Falta Cometida
  PC: -1.0  # Pênalti Cometido
  GC: -5.0  # Gol Contra
  DP: 7.0   # Defesa de Pênalti
  DS: 1.0   # DeSarme 
  DE: 1.0   # DEfesa *

# * exclusivo de goleiro
# ** não válido para goleiros
